spring:
  datasource:
    url: jdbc:h2:mem:estore
    username: sa
    password:
    driverClassName: org.h2.Driver
    validation-query: SELECT 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        dll-auto: none

logging:
  level:
    org:
      springframework:
        security: DEBUG